name: Android CI

on:
  push:
    branches: [ main, develop, 'copilot/**' ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses || true
      
    - name: Install Android SDK components
      run: |
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
        sdkmanager "extras;android;m2repository" "extras;google;m2repository"
      
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
      
    - name: Run unit tests
      run: ./gradlew test --stacktrace
      continue-on-error: true
      
    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Build release APK
      run: ./gradlew assembleRelease --stacktrace
      continue-on-error: true
      
    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: logicam-debug-apk
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 30
        
    - name: Upload release APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: logicam-release-apk
        path: app/build/outputs/apk/release/*.apk
        retention-days: 30
        
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses || true
      
    - name: Install Android SDK components
      run: |
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
        
    - name: Run lint
      run: ./gradlew lint --stacktrace
      continue-on-error: true
      
    - name: Upload lint report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-report
        path: app/build/reports/lint-results*.html
        retention-days: 7
